export const CURRENCY_EXCHANGE_RATE = 'CURRENCY_EXCHANGE_RATE';
export const DIGITAL_CURRENCY_DAILY = 'DIGITAL_CURRENCY_DAILY';
export const DIGITAL_CURRENCY_WEEKLY = 'DIGITAL_CURRENCY_WEEKLY';
export const DIGITAL_CURRENCY_MONTHLY = 'DIGITAL_CURRENCY_MONTHLY';
export const DYNAMIC = '[dynamic]';
export const DYNAMIC_FORMAT = '[dynamicFormat]';
